import React, { createContext, useContext, useState, useCallback, useEffect } from 'react';

export type Language = 'en' | 'lt';

// Translation keys type
type TranslationKeys = typeof translations.en;

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: keyof TranslationKeys) => string;
  formatPrice: (price: number) => string;
}

const translations = {
  en: {
    // Navigation tabs
    'nav.restaurant': 'Restaurant',
    'nav.settings': 'Settings',
    'nav.workday': 'Workday',
    'nav.orders': 'Orders',
    'nav.kitchen': 'Kitchen',
    'nav.history': 'History',

    // TopBar
    'topbar.selectRestaurant': 'Select Restaurant',
    'topbar.logout': 'Log out',
    'topbar.notifications': 'Notifications',
    'topbar.noNotifications': 'No notifications',
    'topbar.activeUsers': 'Active Users',
    'topbar.usersOnline': 'users online',
    'topbar.noUsersOnline': 'No users online',

    // Time
    'time.justNow': 'just now',
    'time.minAgo': 'min ago',
    'time.hourAgo': 'h ago',

    // Settings page
    'settings.title': 'Settings',
    'settings.profile': 'Profile',
    'settings.name': 'Name',
    'settings.email': 'Email',
    'settings.role': 'Role',
    'settings.appTheme': 'App Theme',
    'settings.themeDescription': 'Switch between light and dark mode',
    'settings.light': 'Light',
    'settings.dark': 'Dark',
    'settings.language': 'Language',
    'settings.languageDescription': 'Choose your preferred language',
    'settings.menus': 'Menus',
    'settings.menusDescription': 'Manage restaurant menus and items',
    'settings.createMenu': 'Create Menu',
    'settings.tableLayouts': 'Floor Layouts',
    'settings.tableLayoutsDescription': 'Manage table arrangements',
    'settings.createLayout': 'Create Layout',
    'settings.noMenus': 'No menus created yet',
    'settings.noLayouts': 'No table layouts created yet',
    'settings.editProfile': 'Edit Profile',
    'settings.editProfileDesc': 'Update your profile information',
    'settings.changePhoto': 'Change Photo',

    // Restaurant page
    'restaurant.title': 'Restaurant',
    'restaurant.workers': 'Workers',
    'restaurant.noWorkers': 'No workers assigned yet',
    'restaurant.workersWillAppear': 'Workers will appear here when they join',
    'restaurant.selectRestaurant': 'Select a Restaurant',
    'restaurant.selectRestaurantDescription': 'Choose a restaurant to manage from the list above',
    'restaurant.revenue': 'Revenue',
    'restaurant.clients': 'Clients',
    'restaurant.uniqueTables': 'Unique tables served',
    'restaurant.topItems': 'Top Items',
    'restaurant.topDishes': 'Top Dishes',
    'restaurant.noItems': 'No data available',
    'restaurant.staffManagement': 'Staff Management',
    'restaurant.manageTeam': 'Manage your team and permissions',
    'restaurant.menuDesigner': 'Menu Designer',
    'restaurant.createEditMenus': 'Create and edit menus',
    'restaurant.floorLayouts': 'Floor Layouts',
    'restaurant.manageLayouts': 'Manage table arrangements',
    'restaurant.reminders': 'Reminders',
    'restaurant.noReminders': 'No reminders yet',
    'restaurant.reminderPlaceholder': 'Add a reminder...',
    'restaurant.reminderAdded': 'Reminder added',
    'restaurant.reminderAddedDesc': 'Your reminder has been saved.',
    'restaurant.reminderDeleted': 'Reminder deleted',
    'restaurant.reminderError': 'Failed to add reminder.',
    'restaurant.noRestaurant': 'No Restaurant Selected',
    'restaurant.selectFromTopBar': 'Select a restaurant from the top bar to get started.',
    'restaurant.adminOnly': 'Restaurant management is only available for administrators.',
    'restaurant.staff': 'Staff',
    'restaurant.viewTeam': 'View team members',
    'restaurant.viewCreateMenus': 'View and create menus',
    'restaurant.topStaff': 'Top Staff',
    'restaurant.noStaffData': 'No staff data available',
    'restaurant.viewCreateLayouts': 'View and create layouts',

    // Timeframes
    'timeframe.day': 'Day',
    'timeframe.week': 'Week',
    'timeframe.month': 'Month',
    'timeframe.quarter': 'Quarter',
    'timeframe.year': 'Year',

    // Workday page
    'workday.title': 'Workday',
    'workday.selectMenu': 'Select Menu',
    'workday.selectMenuDescription': 'Choose which menu to use for today',
    'workday.chooseMenu': 'Choose a menu...',
    'workday.selectTableLayout': 'Select Table Layout',
    'workday.selectTableLayoutDescription': 'Choose which table arrangement to use',
    'workday.chooseLayout': 'Choose a layout...',
    'workday.letsGetToWork': "Let's Get to Work!",
    'workday.starting': 'Starting...',
    'workday.selectBothRequired': 'Select both a menu and table layout to start the workday',
    'workday.noMenusAvailable': 'No menus available. Create one in Settings.',
    'workday.noLayoutsAvailable': 'No table layouts available. Create one in Settings.',
    'workday.active': 'Workday Active',
    'workday.startedAt': 'Started at',
    'workday.endWorkday': 'End Workday',
    'workday.ending': 'Ending...',
    'workday.startWorkday': 'Start Workday',
    'workday.readyToStart': 'Ready to start!',
    'workday.startWorkdayConfirmTitle': 'Start Workday?',
    'workday.startWorkdayConfirmDescription': 'Are you sure you want to start the workday? Make sure you have selected the correct menu and table layout.',
    'workday.currentConfig': 'Current Configuration',
    'workday.menu': 'Menu',
    'workday.layout': 'Layout',
    'workday.date': 'Date',
    'workday.today': 'Today',
    'workday.noRestaurantSelected': 'No Restaurant Selected',
    'workday.selectRestaurantFirst': 'Please select a restaurant from the Restaurant tab to manage workdays.',
    'workday.started': 'Workday started!',
    'workday.startedDescription': "Let's get to work! Good luck today!",
    'workday.ended': 'Workday ended',
    'workday.endedDescription': 'Great work today! See you next time.',
    'workday.failedToStart': 'Failed to start workday',
    'workday.failedToEnd': 'Failed to end workday',
    'workday.configRequired': 'Configuration required',
    'workday.selectMenuAndLayout': 'Please select both a menu and a table layout',
    'workday.selectWorkers': 'Select Workers',
    'workday.selectWorkersDescription': 'Who is working today?',
    'workday.noWorkersAvailable': 'No workers available',
    'workday.selected': 'selected',
    'workday.workersOnShift': 'Workers on Shift',
    'workday.activeNow': 'active now',
    'workday.add': 'Add',
    'workday.noWorkersAssigned': 'No workers assigned',
    'workday.working': 'Working',
    'workday.onBreak': 'On break',
    'workday.shiftEnded': 'Shift ended',
    'workday.start': 'Start',
    'workday.rest': 'Rest',
    'workday.done': 'Done',
    'workday.workdaySetup': 'Workday Setup',
    'workday.endWorkdayConfirmTitle': 'End Workday?',
    'workday.endWorkdayConfirmDescription': 'Are you sure you want to end the workday? This will close all active sessions.',
    'workday.addWorkerTitle': 'Add Worker to Shift',
    'workday.addWorkerDescription': 'Select a worker to add to today\'s shift',
    'workday.allWorkersAssigned': 'All workers are already assigned',
    'workday.shiftEndedToday': 'Shift Already Ended Today',
    'workday.shiftsEndedToday': 'Shifts Ended Today',
    'workday.shift': 'Shift',
    'workday.duration': 'Duration',
    'workday.workers': 'workers',
    'workday.endedAt': 'Ended at',
    'workday.online': 'Online',
    'workday.offline': 'Offline',
    'workday.worked': 'Worked',
    'workday.rested': 'Rested',
    'workday.dismissShiftsTitle': 'Dismiss Shift History?',
    'workday.dismissShiftsDescription': 'Are you sure you want to dismiss all ended shift banners? The shift data will still be saved, but the banners will be hidden until tomorrow.',

    // Orders page
    'orders.title': 'Orders',
    'orders.tables': 'Tables',
    'orders.noTables': 'No tables in this layout',
    'orders.people': 'people',
    'orders.noOrders': 'No orders yet. Add items below.',
    'orders.total': 'Total',
    'orders.addItems': 'Add Items',
    'orders.specialItem': 'Special Item',
    'orders.addNote': 'Add a note for this order...',
    'orders.close': 'Close',
    'orders.activateTable': 'Activate Table',
    'orders.numberOfPeople': 'Number of People',
    'orders.howManyPeople': 'How many people are sitting at this table?',
    'orders.cancel': 'Cancel',
    'orders.activate': 'Activate',
    'orders.addSpecialItem': 'Add Special Item',
    'orders.addCustomItem': "Add a custom item that's not on the menu",
    'orders.itemName': 'Item Name',
    'orders.itemNamePlaceholder': 'e.g., Birthday Cake',
    'orders.price': 'Price',
    'orders.addItem': 'Add Item',
    'orders.tableActivated': 'Table activated',
    'orders.tableReady': 'Table is now ready for orders',
    'orders.tableClosed': 'Table closed',
    'orders.tableHasBeenClosed': 'Table has been closed',
    'orders.noActiveWorkday': 'No Active Workday',
    'orders.startWorkdayFirst': 'Start a workday from the Workday tab to manage orders.',
    'orders.special': 'Special',
    'orders.note': 'Note',
    'orders.table': 'Table',
    'orders.tapToActivate': 'Tap to activate',
    'orders.pendingOrder': 'Pending Order',
    'orders.subtotal': 'Subtotal',
    'orders.confirmOrder': 'Send to Kitchen',
    'orders.orderConfirmed': 'Order sent to kitchen!',
    'orders.orderFailed': 'Failed to send order',
    'orders.confirmedOrders': 'Confirmed Orders',
    'orders.ready': 'Ready',
    'orders.badges': 'Badges',
    'orders.addBadge': 'Add',
    'orders.addToOrder': 'Add to Order',
    'orders.closeTableConfirm': 'Close Table?',
    'orders.closeTableWarning': 'Are you sure you want to close this table? All orders will be saved to history.',
    'orders.totalOrders': 'Total Orders',
    'orders.confirmClose': 'Yes, Close Table',
    'orders.unfinishedOrdersWarning': 'Orders still in progress!',
    'orders.unfinishedOrdersMessage': 'There are orders that have not been completed by the kitchen. These will be marked as canceled if you close the table.',
    'orders.unfinishedOrders': 'Unfinished Orders',
    'orders.closeAnyway': 'Close Anyway',
    'orders.tapToOpen': 'Tap to open',
    'orders.openTable': 'Open Table',
    'orders.open': 'Open',
    'orders.editBadges': 'Edit',
    'orders.badgeName': 'Badge name',
    'orders.uncategorized': 'Uncategorized',
    'orders.glutenFree': 'Gluten free',
    'orders.makeItSpecial': 'Make it special',
    'orders.birthday': 'Birthday',
    'orders.child': 'Child',

    // Kitchen page
    'kitchen.title': 'Kitchen',
    'kitchen.noActiveTables': 'No active tables',
    'kitchen.waitingForOrders': 'Waiting for orders to come in',
    'kitchen.noActiveWorkday': 'No Active Workday',
    'kitchen.startWorkdayFirst': 'Start a workday from the Workday tab to view kitchen orders.',
    'kitchen.pendingOrders': 'pending orders',
    'kitchen.allCompleted': 'All completed',
    'kitchen.ready': 'Ready',
    'kitchen.readyAll': 'Ready All',
    'kitchen.undo': 'Undo',
    'kitchen.history': 'History',
    'kitchen.kitchenHistory': 'Kitchen History',
    'kitchen.noCompletedOrders': 'No completed orders yet',
    'kitchen.canceled': 'Canceled',
    'kitchen.closed': 'Closed',
    'kitchen.completed': 'Completed',
    'kitchen.selectToRevoke': 'Select to revoke',
    'kitchen.tableClosedRevoke': 'Table closed - revoke not available',
    'kitchen.revokeItems': 'Revoke',
    'kitchen.waiting': 'waiting',
    'kitchen.pending': 'pending',
    'kitchen.allCaughtUp': 'All Caught Up!',
    'kitchen.noPendingOrders': 'No pending orders right now. New orders will appear here automatically.',
    'kitchen.tablesInHistory': 'tables in history',
    'kitchen.table': 'Table',
    'kitchen.items': 'items',

    // History page
    'history.title': 'History',
    'history.dailyStats': 'Daily statistics & orders',
    'history.daySummary': 'Day Summary',
    'history.totalRevenue': 'Total Revenue',
    'history.totalOrders': 'Total Orders',
    'history.ordersCount': 'Orders',
    'history.tablesServed': 'Tables Served',
    'history.guestsServed': 'Guests Served',
    'history.noData': 'No data for this day',
    'history.selectDate': 'Select a different date to view history',
    'history.shift': 'Shift',
    'history.live': 'Live',
    'history.revenue': 'Revenue',
    'history.orders': 'Orders',
    'history.tables': 'Tables',
    'history.guests': 'Guests',
    'history.workers': 'Workers',
    'history.tableBreakdown': 'Table Breakdown',
    'history.sessions': 'sessions',
    'history.items': 'items',
    'history.started': 'Started',
    'history.table': 'Table',
    'history.special': 'Special',
    'history.liveUpdates': 'Live Updates',
    'history.export': 'Export',
    'history.today': 'Today',
    'history.goToToday': 'Go to Today',
    'history.noActivity': 'No Activity',
    'history.noShiftsRecorded': 'No shifts or orders recorded for this day.',
    'history.startWorkdayToTrack': 'Start a workday to begin tracking.',
    'history.shiftsCount': 'shifts',
    'history.noWorkerData': 'No worker data recorded',
    'history.multipleShifts': 'Multiple Shifts Today',
    'history.combinedTotals': 'Above stats are combined totals.',
    'history.exportReport': 'Export Report',
    'history.downloadExcel': 'Download Excel report to your device',
    'history.dateRange': 'Date Range',
    'history.selectDateRange': 'Select date range...',
    'history.last7Days': 'Last 7 days',
    'history.last30Days': 'Last 30 days',
    'history.generating': 'Generating...',
    'history.downloadReport': 'Download Report',
    'history.notStarted': 'Not started',
    'history.ongoing': 'ongoing',
    'history.lessThan1m': '< 1m',
    'history.noOrdersInShift': 'No orders in this shift yet',
    'history.selectRestaurant': 'Select a restaurant to view history',

    // Settings sidebar
    'settings.appearance': 'Appearance',
    'settings.saving': 'Saving...',
    'settings.notifications': 'Notifications',
    'settings.pushNotifications': 'Push Notifications',
    'settings.enabled': 'Enabled',
    'settings.disabled': 'Disabled',
    'settings.sounds': 'Sounds',
    'settings.support': 'Support',
    'settings.helpSupport': 'Help & Support',
    'settings.privacyPolicy': 'Privacy Policy',
    'settings.admin': 'Admin',
    'settings.cleanAccounts': 'Clean Inactive Accounts',
    'settings.cleanAccountsDesc': 'Remove stale data from cloud',
    'settings.cleaning': 'Cleaning...',
    'settings.appVersion': 'App Version',
    'settings.logOut': 'Log out',
    'settings.changePassword': 'Change Password',
    'settings.updatePassword': 'Update your account password',
    'settings.currentPassword': 'Current Password',
    'settings.enterCurrentPassword': 'Enter current password',
    'settings.newPassword': 'New Password',
    'settings.enterNewPassword': 'Enter new password',
    'settings.confirmNewPassword': 'Confirm New Password',
    'settings.confirmNewPasswordPlaceholder': 'Confirm new password',
    'settings.changing': 'Changing...',
    'settings.updateInfo': 'Update your information',
    'settings.displayName': 'Display Name',
    'settings.enterYourName': 'Enter your name',
    'settings.emailAddress': 'Email Address',
    'settings.saveChanges': 'Save Changes',
    'settings.fullAccess': 'Full Access',
    'settings.limited': 'Limited',

    // Staff / Workers modal
    'staff.title': 'Staff',
    'staff.teamMembers': 'team members',
    'staff.noStaffFound': 'No staff members found',
    'staff.management': 'Staff Management',
    'staff.approvedMembers': 'Approved members',
    'staff.pendingRequests': 'Pending Requests',
    'staff.approve': 'Approve',
    'staff.decline': 'Decline',
    'staff.roleAdmin': 'Admin',
    'staff.roleKitchen': 'Kitchen',
    'staff.roleFloor': 'Floor',
    'staff.approvedStaff': 'Approved Staff',
    'staff.noApprovedStaff': 'No approved staff found',
    'staff.allRestaurants': 'All restaurants',
    'staff.restaurants': 'restaurants',
    'staff.assignToRestaurants': 'Assign to restaurants',
    'staff.noRestaurantsAvailable': 'No restaurants available',
    'staff.accessToAll': 'Access to all restaurants',
    'staff.onlySelected': 'Only selected restaurants',
    'staff.confirmRoleChange': 'Confirm Role Change',
    'staff.confirmChange': 'Confirm Change',
    'staff.removeStaffMember': 'Remove Staff Member',
    'staff.remove': 'Remove',

    // Login page
    'login.signIn': 'Sign In',
    'login.requestAccess': 'Request Access',
    'login.continueWithGoogle': 'Continue with Google',
    'login.orContinueWithEmail': 'or continue with email',
    'login.fullName': 'Full Name',
    'login.enterFullName': 'Enter your full name',
    'login.emailAddress': 'Email Address',
    'login.enterEmail': 'Enter your email',
    'login.password': 'Password',
    'login.enterPassword': 'Enter your password',
    'login.confirmPassword': 'Confirm Password',
    'login.confirmYourPassword': 'Confirm your password',
    'login.requestReview': 'Your request will be reviewed by an administrator. You\'ll be notified once approved.',

    // Common
    'common.loading': 'Loading...',
    'common.error': 'Error',
    'common.success': 'Success',
    'common.save': 'Save',
    'common.delete': 'Delete',
    'common.edit': 'Edit',
    'common.create': 'Create',
    'common.notSet': 'Not set',
    'common.somethingWentWrong': 'Something went wrong',
    'common.showMore': 'Show all',
    'common.showLess': 'Show less',
    'common.accessRestricted': 'Access Restricted',
    'common.cancel': 'Cancel',
    'common.saving': 'Saving...',
    'common.close': 'Close',
    'common.dismissAll': 'Dismiss All',
    'common.dismiss': 'Dismiss',
    'common.done': 'Done',

    // Toasts
    'toast.restaurantSelected': 'Restaurant Selected',
    'toast.restaurantSelectedDescription': 'is now active.',
    'toast.notificationSent': 'Notification sent',
    'toast.kitchenNotified': 'Kitchen has been notified',

    // Roles
    'role.admin': 'admin',
    'role.manager': 'manager',
    'role.worker': 'worker',
    'role.kitchen': 'kitchen',
    'roles.admin': 'Admin',
    'roles.manager': 'Manager',
    'roles.worker': 'Worker',
    'roles.kitchen': 'Kitchen',

    // Restaurant modal
    'modal.selectRestaurant': 'Select Restaurant',
    'modal.chooseRestaurant': 'Choose a restaurant to manage',
    'modal.noRestaurants': 'No restaurants available',
    'modal.createRestaurant': 'Create a new restaurant to get started',

    // Restaurant Board
    'board.title': 'Restaurant Board',
    'board.note': 'note',
    'board.notes': 'notes',
    'board.noNotes': 'No notes yet. Add one below!',
    'board.addNote': 'Add a note to the board...',
    'board.markedImportant': 'Marked as important',
    'board.markImportant': 'Mark as important',

    // Menu Designer
    'menu.designer': 'Menu Designer',
    'menu.manageCategoriesItems': 'Manage categories and items',
    'menu.menusCount': 'menus',
    'menu.noRestaurant': 'No Restaurant Selected',
    'menu.selectRestaurantFirst': 'Please select a restaurant first.',
    'menu.editMenu': 'Edit Menu',
    'menu.createNewMenu': 'Create New Menu',
    'menu.menuName': 'Menu Name',
    'menu.update': 'Update',
    'menu.noMenus': 'No menus yet',
    'menu.clickToManage': 'Click to manage',
    'menu.deleteMenu': 'Delete Menu',
    'menu.deleteAndAllItems': 'and all its categories and items?',
    'menu.menuCreated': 'Menu Created',
    'menu.menuCreatedDesc': 'Menu has been created successfully.',
    'menu.menuUpdated': 'Menu Updated',
    'menu.menuUpdatedDesc': 'Menu has been updated successfully.',
    'menu.menuDeleted': 'Menu Deleted',
    'menu.menuDeletedDesc': 'Menu has been deleted successfully.',
    'menu.failedCreate': 'Failed to create menu.',
    'menu.failedUpdate': 'Failed to update menu.',
    'menu.failedDelete': 'Failed to delete menu.',
    'menu.addCategory': 'Add Category',
    'menu.editCategory': 'Edit Category',
    'menu.categoryName': 'Category Name',
    'menu.noCategories': 'No categories yet',
    'menu.addItem': 'Add Item',
    'menu.editItem': 'Edit Item',
    'menu.itemName': 'Item Name',
    'menu.price': 'Price',
    'menu.descriptionOptional': 'Description (Optional)',
    'menu.noItems': 'No items in this category',
    'menu.deleteItem': 'Delete Item',
    'menu.deleteCategory': 'Delete Category',
    'menu.deleteCategoryAndItems': 'and all its items?',
    'menu.categoryCreated': 'Category Created',
    'menu.categoryCreatedDesc': 'Category has been created successfully.',
    'menu.categoryUpdated': 'Category Updated',
    'menu.categoryUpdatedDesc': 'Category has been updated successfully.',
    'menu.categoryDeleted': 'Category Deleted',
    'menu.categoryDeletedDesc': 'Category has been deleted.',
    'menu.failedCreateCategory': 'Failed to create category.',
    'menu.failedUpdateCategory': 'Failed to update category.',
    'menu.failedDeleteCategory': 'Failed to delete category.',
    'menu.itemCreated': 'Item Created',
    'menu.itemCreatedDesc': 'Menu item has been created successfully.',
    'menu.itemUpdated': 'Item Updated',
    'menu.itemUpdatedDesc': 'Menu item has been updated successfully.',
    'menu.itemDeleted': 'Item Deleted',
    'menu.itemDeletedDesc': 'Menu item has been deleted.',
    'menu.failedCreateItem': 'Failed to create item.',
    'menu.failedUpdateItem': 'Failed to update item.',
    'menu.failedDeleteItem': 'Failed to delete item.',
    'menu.invalidPrice': 'Invalid Price',
    'menu.enterValidPrice': 'Please enter a valid price.',
    'menu.item': 'item',
    'menu.items': 'items',

    // Floor Layouts
    'layout.floorLayouts': 'Floor Layouts',
    'layout.tables': 'tables',
    'layout.layouts': 'layouts',
    'layout.editTable': 'Edit Table',
    'layout.addNewTable': 'Add New Table',
    'layout.tableNumber': 'Table Number',
    'layout.description': 'Description',
    'layout.addTable': 'Add Table',
    'layout.noTables': 'No tables yet',
    'layout.table': 'Table',
    'layout.editLayout': 'Edit Layout',
    'layout.createNewLayout': 'Create New Layout',
    'layout.layoutName': 'Layout Name',
    'layout.noLayouts': 'No layouts yet',
    'layout.selectLayout': 'Select Layout',
    'layout.deleteLayout': 'Delete Layout',
    'layout.deleteLayoutDesc': 'This will also delete all tables within this layout.',
    'layout.deleteTable': 'Delete Table',
    'layout.tableAdded': 'Table was added successfully.',
    'layout.tableUpdated': 'Table was updated successfully.',
    'layout.tableDeleted': 'Table was deleted successfully.',
    'layout.layoutCreated': 'Layout was created successfully.',
    'layout.layoutUpdated': 'Layout was updated successfully.',
    'layout.layoutDeleted': 'Layout was deleted successfully.',
    'layout.failedCreateTable': 'Failed to create table.',
    'layout.failedUpdateTable': 'Failed to update table.',
    'layout.failedDeleteTable': 'Failed to delete table.',
    'layout.failedCreateLayout': 'Failed to create layout.',
    'layout.failedUpdateLayout': 'Failed to update layout.',
    'layout.failedDeleteLayout': 'Failed to delete layout.',
    'layout.table1': 'table',

    // Help & Support
    'help.title': 'Help & Support',
    'help.welcomeTitle': 'Welcome, Brave Soul!',
    'help.welcomeText': "You've found the Help page. Congratulations. Most people just panic and call the manager. You're already ahead of 99% of the staff. This app is basically the Avengers headquarters, but instead of saving the world, you're saving dinner orders from chaos.",
    'help.howTitle': 'How Did I Get Here?',
    'help.howText': "Someone (probably your boss) approved your account. You've been assigned a role — Floor, Kitchen, or Admin. Think of it like Hogwarts houses, except no one picks their own and the Sorting Hat is your manager. If you got Kitchen, don't worry — at least it's warm in there.",
    'help.buttonsTitle': 'What Do All These Buttons Do?',
    'help.ordersDesc': 'Where the magic happens. Take orders like a pro. Or at least like someone who\'s trying really, really hard.',
    'help.kitchenDesc': 'Real-time orders for the kitchen crew. No more playing telephone across the restaurant. "DID YOU SAY NO ONIONS OR EXTRA ONIONS?!" — never again.',
    'help.workdayDesc': 'Clock in, track shifts, pretend you arrived on time. (We see the timestamps, by the way.)',
    'help.historyDesc': "Every order ever made. It's like your browser history, but for food and actually useful.",
    'help.restaurantDesc': "Admin-only territory. If you see this tab, you either have power or you found a bug. Either way, use it wisely.",
    'help.tipsTitle': 'Pro Tips (You\'re Welcome)',
    'help.tip1': "Install the app on your phone. It works like a real app! Your phone won't even know the difference. We've fooled millions of phones worldwide. (Okay, maybe like 4.)",
    'help.tip2': "Orders update in real-time on every device simultaneously. It's not magic — it's technology that the developer spent way too many nights building instead of sleeping.",
    'help.tip3': 'Try dark mode during late shifts. Your retinas will write you a thank-you letter.',
    'help.tip4': "If something looks broken, try refreshing. If it's still broken, it's a \"feature.\" If it's REALLY broken, blame the developer — he probably deserves it.",
    'help.actualHelpTitle': 'I Need Actual Help Though',
    'help.actualHelpText': "If the app crashes, your orders vanish, or the kitchen screen starts showing cat videos — contact your administrator. They'll fix it, or they'll forward your complaint to the developer, who will read it at 2 AM while questioning his life choices. Either way, someone will respond. Probably. Eventually. We promise nothing but we'll try our best.",
    'help.footer': 'Handcrafted with mass amounts of caffeine by Justinas Narutis. v1.0.0 — "It works on my machine" edition.',

    // Privacy Policy
    'privacy.title': 'Privacy Policy',
    'privacy.lastUpdated': "Last updated: February 2026. You're probably the first person to actually open this page. We're genuinely impressed. Your mom would be proud.",
    'privacy.collectTitle': "What We Collect (Don't Panic)",
    'privacy.collectText': "We collect your name, email, and role at the restaurant. That's it. We're not the CIA. We don't know your location, your search history, or that you Googled \"how to quit my job professionally\" last Tuesday. We also store order data and shift records, because someone has to remember that Table 7 ordered the fish special. We do NOT collect: your Spotify playlists, your Tinder bio, your controversial pizza topping opinions, or your Netflix password (though if you're offering...).",
    'privacy.useTitle': 'What We Do With Your Data',
    'privacy.useText': "We use it to run the restaurant app. That's literally it. We process orders, track who worked when, and generate reports that make the boss feel important. We do NOT sell your data. We do NOT share it with advertisers. We do NOT trade it on the black market. We don't even look at it for fun. Honestly, your order history isn't that interesting. (Though whoever keeps ordering extra bread — we see you, and we respect you.)",
    'privacy.whereTitle': 'Where Your Data Lives',
    'privacy.whereText': "Your login stuff lives in Firebase (that's Google — yes, THAT Google, the one that knows everything about everyone except us, because we don't share). Your restaurant data lives on a server that the developer personally guards with his life. Okay, not his life, but at least a strong password. Everything is encrypted with HTTPS/SSL, which is a fancy way of saying \"hackers would have an easier time breaking into Fort Knox.\" Your data is backed up daily, because unlike your ex, we believe in second chances and never losing what matters.",
    'privacy.rightsTitle': 'Your Sacred Rights',
    'privacy.right1': "You can ask to see all the data we have on you. Spoiler: it's your name, email, and that time you accidentally sent an order for 47 soups.",
    'privacy.right2': "You can ask your admin to delete your account. We'll be sad, but we'll survive. Probably.",
    'privacy.right3': 'You can change your password anytime. Please don\'t make it "password123." We beg you.',
    'privacy.right4': "You have the right to complain. We have the right to respond with a shrug emoji. But we'll still try to fix it.",
    'privacy.right5': 'You have the right to remain confused. Anything you click can and will be used to take a food order.',
    'privacy.cookiesTitle': 'Cookies (The Digital Kind, Sadly)',
    'privacy.cookiesText': "We use exactly ONE type of cookie: the kind that keeps you logged in so you don't have to enter your password 47 times per shift. No advertising cookies. No tracking pixels. No creepy \"we noticed you looked at running shoes\" ads following you around the internet. The only cookies we truly care about are the chocolate chip ones on the dessert menu. Speaking of which, have you tried them? They're excellent. This is not a sponsored message — we just really like cookies.",
    'privacy.changeTitle': 'Will This Policy Change?',
    'privacy.changeText': "Maybe. But if it does, we promise it'll still be written by a human who thinks legal documents should be readable without a law degree and three espressos. We'll never sneak in \"by using this app you agree to give us your firstborn child\" clauses. Pinky promise.",
    'privacy.footer': "Questions? Complaints? Existential crises? Contact your administrator. They'll pretend to know the answer.",
  },
  lt: {
    // Navigation tabs
    'nav.restaurant': 'Restoranas',
    'nav.settings': 'Nustatymai',
    'nav.workday': 'Darbo diena',
    'nav.orders': 'Užsakymai',
    'nav.kitchen': 'Virtuvė',
    'nav.history': 'Istorija',

    // TopBar
    'topbar.selectRestaurant': 'Pasirinkti restoraną',
    'topbar.logout': 'Atsijungti',
    'topbar.notifications': 'Pranešimai',
    'topbar.noNotifications': 'Pranešimų nėra',
    'topbar.activeUsers': 'Aktyvūs vartotojai',
    'topbar.usersOnline': 'prisijungę',
    'topbar.noUsersOnline': 'Nėra prisijungusių',

    // Time
    'time.justNow': 'ką tik',
    'time.minAgo': 'min. prieš',
    'time.hourAgo': 'val. prieš',

    // Settings page
    'settings.title': 'Nustatymai',
    'settings.profile': 'Profilis',
    'settings.name': 'Vardas',
    'settings.email': 'El. paštas',
    'settings.role': 'Rolė',
    'settings.appTheme': 'Programos tema',
    'settings.themeDescription': 'Perjungti tarp šviesios ir tamsios temos',
    'settings.light': 'Šviesi',
    'settings.dark': 'Tamsi',
    'settings.language': 'Kalba',
    'settings.languageDescription': 'Pasirinkite norimą kalbą',
    'settings.menus': 'Meniu',
    'settings.menusDescription': 'Valdyti restorano meniu ir patiekalus',
    'settings.createMenu': 'Sukurti meniu',
    'settings.tableLayouts': 'Salės išdėstymai',
    'settings.tableLayoutsDescription': 'Valdyti stalų išdėstymus',
    'settings.createLayout': 'Sukurti išdėstymą',
    'settings.noMenus': 'Meniu dar nesukurta',
    'settings.noLayouts': 'Stalų išdėstymų dar nesukurta',
    'settings.editProfile': 'Redaguoti profilį',
    'settings.editProfileDesc': 'Atnaujinti profilio informaciją',
    'settings.changePhoto': 'Keisti nuotrauką',

    // Restaurant page
    'restaurant.title': 'Restoranas',
    'restaurant.workers': 'Darbuotojai',
    'restaurant.noWorkers': 'Darbuotojų dar nepriskirta',
    'restaurant.workersWillAppear': 'Darbuotojai pasirodys čia, kai prisijungs',
    'restaurant.selectRestaurant': 'Pasirinkite restoraną',
    'restaurant.selectRestaurantDescription': 'Pasirinkite restoraną valdymui iš sąrašo aukščiau',
    'restaurant.revenue': 'Pajamos',
    'restaurant.clients': 'Klientai',
    'restaurant.uniqueTables': 'Aptarnauti stalai',
    'restaurant.topItems': 'Populiariausi',
    'restaurant.topDishes': 'Populiariausi patiekalai',
    'restaurant.noItems': 'Duomenų nėra',
    'restaurant.staffManagement': 'Personalo valdymas',
    'restaurant.manageTeam': 'Valdyti komandą ir leidimus',
    'restaurant.menuDesigner': 'Meniu dizaineris',
    'restaurant.createEditMenus': 'Kurti ir redaguoti meniu',
    'restaurant.floorLayouts': 'Salės išdėstymai',
    'restaurant.manageLayouts': 'Valdyti stalų išdėstymus',
    'restaurant.reminders': 'Priminimai',
    'restaurant.noReminders': 'Priminimų dar nėra',
    'restaurant.reminderPlaceholder': 'Pridėti priminimą...',
    'restaurant.reminderAdded': 'Priminimas pridėtas',
    'restaurant.reminderAddedDesc': 'Jūsų priminimas išsaugotas.',
    'restaurant.reminderDeleted': 'Priminimas ištrintas',
    'restaurant.reminderError': 'Nepavyko pridėti priminimo.',
    'restaurant.noRestaurant': 'Restoranas nepasirinktas',
    'restaurant.selectFromTopBar': 'Pasirinkite restoraną iš viršutinės juostos.',
    'restaurant.adminOnly': 'Restorano valdymas prieinamas tik administratoriams.',
    'restaurant.staff': 'Personalas',
    'restaurant.viewTeam': 'Peržiūrėti komandą',
    'restaurant.viewCreateMenus': 'Peržiūrėti ir kurti meniu',
    'restaurant.topStaff': 'Geriausi darbuotojai',
    'restaurant.noStaffData': 'Darbuotojų duomenų nėra',
    'restaurant.viewCreateLayouts': 'Peržiūrėti ir kurti išdėstymus',

    // Timeframes
    'timeframe.day': 'Diena',
    'timeframe.week': 'Savaitė',
    'timeframe.month': 'Mėnuo',
    'timeframe.quarter': 'Ketvirtis',
    'timeframe.year': 'Metai',

    // Workday page
    'workday.title': 'Darbo diena',
    'workday.selectMenu': 'Pasirinkti meniu',
    'workday.selectMenuDescription': 'Pasirinkite, kurį meniu naudoti šiandien',
    'workday.chooseMenu': 'Pasirinkite meniu...',
    'workday.selectTableLayout': 'Pasirinkti stalų išdėstymą',
    'workday.selectTableLayoutDescription': 'Pasirinkite, kurį stalų išdėstymą naudoti',
    'workday.chooseLayout': 'Pasirinkite išdėstymą...',
    'workday.letsGetToWork': 'Pradėkime darbą!',
    'workday.starting': 'Pradedama...',
    'workday.selectBothRequired': 'Pasirinkite meniu ir stalų išdėstymą, kad pradėtumėte darbo dieną',
    'workday.noMenusAvailable': 'Meniu nėra. Sukurkite jį Nustatymuose.',
    'workday.noLayoutsAvailable': 'Stalų išdėstymų nėra. Sukurkite jį Nustatymuose.',
    'workday.active': 'Darbo diena aktyvi',
    'workday.startedAt': 'Pradėta',
    'workday.endWorkday': 'Baigti darbo dieną',
    'workday.ending': 'Baigiama...',
    'workday.startWorkday': 'Pradėti darbo dieną',
    'workday.readyToStart': 'Pasiruošta pradėti!',
    'workday.startWorkdayConfirmTitle': 'Pradėti darbo dieną?',
    'workday.startWorkdayConfirmDescription': 'Ar tikrai norite pradėti darbo dieną? Įsitikinkite, kad pasirinkote teisingą meniu ir stalų išdėstymą.',
    'workday.currentConfig': 'Dabartinė konfigūracija',
    'workday.menu': 'Meniu',
    'workday.layout': 'Išdėstymas',
    'workday.date': 'Data',
    'workday.today': 'Šiandien',
    'workday.noRestaurantSelected': 'Restoranas nepasirinktas',
    'workday.selectRestaurantFirst': 'Pasirinkite restoraną Restorano skiltyje, kad valdytumėte darbo dienas.',
    'workday.started': 'Darbo diena pradėta!',
    'workday.startedDescription': 'Pradėkime darbą! Sėkmės šiandien!',
    'workday.ended': 'Darbo diena baigta',
    'workday.endedDescription': 'Puikus darbas šiandien! Iki pasimatymo.',
    'workday.failedToStart': 'Nepavyko pradėti darbo dienos',
    'workday.failedToEnd': 'Nepavyko baigti darbo dienos',
    'workday.configRequired': 'Reikalinga konfigūracija',
    'workday.selectMenuAndLayout': 'Pasirinkite meniu ir stalų išdėstymą',
    'workday.selectWorkers': 'Pasirinkti darbuotojus',
    'workday.selectWorkersDescription': 'Kas šiandien dirba?',
    'workday.noWorkersAvailable': 'Darbuotojų nėra',
    'workday.selected': 'pasirinkta',
    'workday.workersOnShift': 'Darbuotojai pamainoje',
    'workday.activeNow': 'dirba dabar',
    'workday.add': 'Pridėti',
    'workday.noWorkersAssigned': 'Darbuotojų nepaskirta',
    'workday.working': 'Dirba',
    'workday.onBreak': 'Pertraukoje',
    'workday.shiftEnded': 'Pamaina baigta',
    'workday.start': 'Pradėti',
    'workday.rest': 'Pertrauka',
    'workday.done': 'Baigta',
    'workday.workdaySetup': 'Darbo dienos nustatymai',
    'workday.endWorkdayConfirmTitle': 'Baigti darbo dieną?',
    'workday.endWorkdayConfirmDescription': 'Ar tikrai norite baigti darbo dieną? Tai uždarys visas aktyvias sesijas.',
    'workday.addWorkerTitle': 'Pridėti darbuotoją į pamainą',
    'workday.addWorkerDescription': 'Pasirinkite darbuotoją, kurį pridėti į šiandienos pamainą',
    'workday.allWorkersAssigned': 'Visi darbuotojai jau paskirti',
    'workday.shiftEndedToday': 'Pamaina jau baigta šiandien',
    'workday.shiftsEndedToday': 'Pamainos baigtos šiandien',
    'workday.shift': 'Pamaina',
    'workday.duration': 'Trukmė',
    'workday.workers': 'darbuotojai',
    'workday.endedAt': 'Baigta',
    'workday.online': 'Prisijungęs',
    'workday.offline': 'Neprisijungęs',
    'workday.worked': 'Dirbo',
    'workday.rested': 'Ilsėjosi',
    'workday.dismissShiftsTitle': 'Paslėpti pamainų istoriją?',
    'workday.dismissShiftsDescription': 'Ar tikrai norite paslėpti visas baigtas pamainas? Pamainų duomenys bus išsaugoti, bet pranešimai bus paslėpti iki rytojaus.',

    // Orders page
    'orders.title': 'Užsakymai',
    'orders.tables': 'Stalai',
    'orders.noTables': 'Šiame išdėstyme stalų nėra',
    'orders.people': 'žmonės',
    'orders.noOrders': 'Užsakymų dar nėra. Pridėkite žemiau.',
    'orders.total': 'Viso',
    'orders.addItems': 'Pridėti patiekalus',
    'orders.specialItem': 'Specialus patiekalas',
    'orders.addNote': 'Pridėti pastabą šiam užsakymui...',
    'orders.close': 'Uždaryti',
    'orders.activateTable': 'Aktyvuoti stalą',
    'orders.numberOfPeople': 'Žmonių skaičius',
    'orders.howManyPeople': 'Kiek žmonių sėdi prie šio stalo?',
    'orders.cancel': 'Atšaukti',
    'orders.activate': 'Aktyvuoti',
    'orders.addSpecialItem': 'Pridėti specialų patiekalą',
    'orders.addCustomItem': 'Pridėti patiekalą, kurio nėra meniu',
    'orders.itemName': 'Patiekalo pavadinimas',
    'orders.itemNamePlaceholder': 'pvz., Gimtadienio tortas',
    'orders.price': 'Kaina',
    'orders.addItem': 'Pridėti',
    'orders.tableActivated': 'Stalas aktyvuotas',
    'orders.tableReady': 'Stalas paruoštas užsakymams',
    'orders.tableClosed': 'Stalas uždarytas',
    'orders.tableHasBeenClosed': 'Stalas buvo uždarytas',
    'orders.noActiveWorkday': 'Nėra aktyvios darbo dienos',
    'orders.startWorkdayFirst': 'Pradėkite darbo dieną Darbo dienos skiltyje, kad valdytumėte užsakymus.',
    'orders.special': 'Specialus',
    'orders.note': 'Pastaba',
    'orders.table': 'Stalas',
    'orders.tapToActivate': 'Paspauskite aktyvuoti',
    'orders.pendingOrder': 'Laukiantis užsakymas',
    'orders.subtotal': 'Tarpinė suma',
    'orders.confirmOrder': 'Siųsti į virtuvę',
    'orders.orderConfirmed': 'Užsakymas išsiųstas į virtuvę!',
    'orders.orderFailed': 'Nepavyko išsiųsti užsakymo',
    'orders.confirmedOrders': 'Patvirtinti užsakymai',
    'orders.ready': 'Paruošta',
    'orders.badges': 'Žymės',
    'orders.addBadge': 'Pridėti',
    'orders.addToOrder': 'Pridėti į užsakymą',
    'orders.closeTableConfirm': 'Uždaryti stalą?',
    'orders.closeTableWarning': 'Ar tikrai norite uždaryti šį stalą? Visi užsakymai bus išsaugoti istorijoje.',
    'orders.totalOrders': 'Iš viso užsakymų',
    'orders.confirmClose': 'Taip, uždaryti',
    'orders.unfinishedOrdersWarning': 'Yra nepabaigti užsakymai!',
    'orders.unfinishedOrdersMessage': 'Yra užsakymų, kurių virtuvė dar nepabaigė. Uždarius stalą, jie bus pažymėti kaip atšaukti.',
    'orders.unfinishedOrders': 'Nepabaigti užsakymai',
    'orders.closeAnyway': 'Vis tiek uždaryti',
    'orders.tapToOpen': 'Paspauskite atidaryti',
    'orders.openTable': 'Atidaryti stalą',
    'orders.open': 'Atidaryti',
    'orders.editBadges': 'Redaguoti',
    'orders.badgeName': 'Žymės pavadinimas',
    'orders.uncategorized': 'Be kategorijos',
    'orders.glutenFree': 'Be gliuteno',
    'orders.makeItSpecial': 'Padaryti ypatingą',
    'orders.birthday': 'Gimtadienis',
    'orders.child': 'Vaikas',

    // Kitchen page
    'kitchen.title': 'Virtuvė',
    'kitchen.noActiveTables': 'Aktyvių stalų nėra',
    'kitchen.waitingForOrders': 'Laukiama užsakymų',
    'kitchen.noActiveWorkday': 'Nėra aktyvios darbo dienos',
    'kitchen.startWorkdayFirst': 'Pradėkite darbo dieną Darbo dienos skiltyje, kad matytumėte virtuvės užsakymus.',
    'kitchen.pendingOrders': 'laukiantys užsakymai',
    'kitchen.allCompleted': 'Visi atlikti',
    'kitchen.ready': 'Paruošta',
    'kitchen.readyAll': 'Paruošti visus',
    'kitchen.undo': 'Atšaukti',
    'kitchen.history': 'Istorija',
    'kitchen.kitchenHistory': 'Virtuvės istorija',
    'kitchen.noCompletedOrders': 'Baigtų užsakymų dar nėra',
    'kitchen.canceled': 'Atšaukta',
    'kitchen.closed': 'Uždaryta',
    'kitchen.completed': 'Atlikta',
    'kitchen.selectToRevoke': 'Pasirinkite atšaukimui',
    'kitchen.tableClosedRevoke': 'Stalas uždarytas - atšaukti negalima',
    'kitchen.revokeItems': 'Atšaukti',
    'kitchen.waiting': 'laukia',
    'kitchen.pending': 'laukiantys',
    'kitchen.allCaughtUp': 'Viskas atlikta!',
    'kitchen.noPendingOrders': 'Šiuo metu laukiančių užsakymų nėra. Nauji užsakymai pasirodys automatiškai.',
    'kitchen.tablesInHistory': 'stalai istorijoje',
    'kitchen.table': 'Stalas',
    'kitchen.items': 'patiekalai',

    // History page
    'history.title': 'Istorija',
    'history.dailyStats': 'Dienos statistika ir užsakymai',
    'history.daySummary': 'Dienos suvestinė',
    'history.totalRevenue': 'Bendra suma',
    'history.totalOrders': 'Iš viso užsakymų',
    'history.ordersCount': 'Užsakymai',
    'history.tablesServed': 'Aptarnauti stalai',
    'history.guestsServed': 'Aptarnauti svečiai',
    'history.noData': 'Šiai dienai duomenų nėra',
    'history.selectDate': 'Pasirinkite kitą datą istorijai peržiūrėti',
    'history.shift': 'Pamaina',
    'history.live': 'Gyvai',
    'history.revenue': 'Pajamos',
    'history.orders': 'Užsakymai',
    'history.tables': 'Stalai',
    'history.guests': 'Svečiai',
    'history.workers': 'Darbuotojai',
    'history.tableBreakdown': 'Stalų suvestinė',
    'history.sessions': 'sesijos',
    'history.items': 'patiekalai',
    'history.started': 'Pradėta',
    'history.table': 'Stalas',
    'history.special': 'Specialus',
    'history.liveUpdates': 'Gyvai atnaujinama',
    'history.export': 'Eksportuoti',
    'history.today': 'Šiandien',
    'history.goToToday': 'Eiti į šiandien',
    'history.noActivity': 'Nėra veiklos',
    'history.noShiftsRecorded': 'Šią dieną pamainų ar užsakymų neužregistruota.',
    'history.startWorkdayToTrack': 'Pradėkite darbo dieną, kad pradėtumėte sekimą.',
    'history.shiftsCount': 'pamainos',
    'history.noWorkerData': 'Darbuotojų duomenų nėra',
    'history.multipleShifts': 'Kelios pamainos šiandien',
    'history.combinedTotals': 'Aukščiau pateikta bendra statistika.',
    'history.exportReport': 'Eksportuoti ataskaitą',
    'history.downloadExcel': 'Atsisiųsti Excel ataskaitą į įrenginį',
    'history.dateRange': 'Datų intervalas',
    'history.selectDateRange': 'Pasirinkite datų intervalą...',
    'history.last7Days': 'Paskutinės 7 dienos',
    'history.last30Days': 'Paskutinės 30 dienų',
    'history.generating': 'Generuojama...',
    'history.downloadReport': 'Atsisiųsti ataskaitą',
    'history.notStarted': 'Nepradėta',
    'history.ongoing': 'vyksta',
    'history.lessThan1m': '< 1 min',
    'history.noOrdersInShift': 'Šioje pamainoje dar nėra užsakymų',
    'history.selectRestaurant': 'Pasirinkite restoraną, kad peržiūrėtumėte istoriją',

    // Settings sidebar
    'settings.appearance': 'Išvaizda',
    'settings.saving': 'Saugoma...',
    'settings.notifications': 'Pranešimai',
    'settings.pushNotifications': 'Push pranešimai',
    'settings.enabled': 'Įjungta',
    'settings.disabled': 'Išjungta',
    'settings.sounds': 'Garsai',
    'settings.support': 'Pagalba',
    'settings.helpSupport': 'Pagalba ir palaikymas',
    'settings.privacyPolicy': 'Privatumo politika',
    'settings.admin': 'Administravimas',
    'settings.cleanAccounts': 'Valyti neaktyvias paskyras',
    'settings.cleanAccountsDesc': 'Pašalinti senus duomenis iš debesies',
    'settings.cleaning': 'Valoma...',
    'settings.appVersion': 'Programos versija',
    'settings.logOut': 'Atsijungti',
    'settings.changePassword': 'Keisti slaptažodį',
    'settings.updatePassword': 'Atnaujinti paskyros slaptažodį',
    'settings.currentPassword': 'Dabartinis slaptažodis',
    'settings.enterCurrentPassword': 'Įveskite dabartinį slaptažodį',
    'settings.newPassword': 'Naujas slaptažodis',
    'settings.enterNewPassword': 'Įveskite naują slaptažodį',
    'settings.confirmNewPassword': 'Patvirtinti naują slaptažodį',
    'settings.confirmNewPasswordPlaceholder': 'Patvirtinkite naują slaptažodį',
    'settings.changing': 'Keičiama...',
    'settings.updateInfo': 'Atnaujinti informaciją',
    'settings.displayName': 'Rodomas vardas',
    'settings.enterYourName': 'Įveskite savo vardą',
    'settings.emailAddress': 'El. pašto adresas',
    'settings.saveChanges': 'Išsaugoti pakeitimus',
    'settings.fullAccess': 'Pilna prieiga',
    'settings.limited': 'Ribota',

    // Staff / Workers modal
    'staff.title': 'Personalas',
    'staff.teamMembers': 'komandos nariai',
    'staff.noStaffFound': 'Darbuotojų nerasta',
    'staff.management': 'Personalo valdymas',
    'staff.approvedMembers': 'Patvirtinti nariai',
    'staff.pendingRequests': 'Laukiančios užklausos',
    'staff.approve': 'Patvirtinti',
    'staff.decline': 'Atmesti',
    'staff.roleAdmin': 'Administratorius',
    'staff.roleKitchen': 'Virtuvė',
    'staff.roleFloor': 'Salė',
    'staff.approvedStaff': 'Patvirtinti darbuotojai',
    'staff.noApprovedStaff': 'Patvirtintų darbuotojų nerasta',
    'staff.allRestaurants': 'Visi restoranai',
    'staff.restaurants': 'restoranai',
    'staff.assignToRestaurants': 'Priskirti restoranams',
    'staff.noRestaurantsAvailable': 'Restoranų nėra',
    'staff.accessToAll': 'Prieiga prie visų restoranų',
    'staff.onlySelected': 'Tik pasirinkti restoranai',
    'staff.confirmRoleChange': 'Patvirtinti rolės keitimą',
    'staff.confirmChange': 'Patvirtinti keitimą',
    'staff.removeStaffMember': 'Pašalinti darbuotoją',
    'staff.remove': 'Pašalinti',

    // Login page
    'login.signIn': 'Prisijungti',
    'login.requestAccess': 'Prašyti prieigos',
    'login.continueWithGoogle': 'Tęsti su Google',
    'login.orContinueWithEmail': 'arba tęsti su el. paštu',
    'login.fullName': 'Vardas ir pavardė',
    'login.enterFullName': 'Įveskite savo vardą',
    'login.emailAddress': 'El. pašto adresas',
    'login.enterEmail': 'Įveskite el. paštą',
    'login.password': 'Slaptažodis',
    'login.enterPassword': 'Įveskite slaptažodį',
    'login.confirmPassword': 'Patvirtinti slaptažodį',
    'login.confirmYourPassword': 'Patvirtinkite slaptažodį',
    'login.requestReview': 'Jūsų užklausa bus peržiūrėta administratoriaus. Būsite informuoti, kai bus patvirtinta.',

    // Common
    'common.loading': 'Kraunama...',
    'common.error': 'Klaida',
    'common.success': 'Sėkmė',
    'common.save': 'Išsaugoti',
    'common.delete': 'Ištrinti',
    'common.edit': 'Redaguoti',
    'common.create': 'Sukurti',
    'common.notSet': 'Nenustatyta',
    'common.somethingWentWrong': 'Kažkas nutiko',
    'common.showMore': 'Rodyti visus',
    'common.showLess': 'Rodyti mažiau',
    'common.accessRestricted': 'Prieiga apribota',
    'common.cancel': 'Atšaukti',
    'common.saving': 'Saugoma...',
    'common.close': 'Uždaryti',
    'common.dismissAll': 'Atmesti visus',
    'common.dismiss': 'Atmesti',
    'common.done': 'Atlikta',

    // Toasts
    'toast.restaurantSelected': 'Restoranas pasirinktas',
    'toast.restaurantSelectedDescription': 'dabar aktyvus.',
    'toast.notificationSent': 'Pranešimas išsiųstas',
    'toast.kitchenNotified': 'Virtuvė informuota',

    // Roles
    'role.admin': 'administratorius',
    'role.manager': 'vadybininkas',
    'role.worker': 'darbuotojas',
    'role.kitchen': 'virtuvė',
    'roles.admin': 'Administratorius',
    'roles.manager': 'Vadybininkas',
    'roles.worker': 'Darbuotojas',
    'roles.kitchen': 'Virtuvė',

    // Restaurant modal
    'modal.selectRestaurant': 'Pasirinkti restoraną',
    'modal.chooseRestaurant': 'Pasirinkite restoraną valdymui',
    'modal.noRestaurants': 'Restoranų nėra',
    'modal.createRestaurant': 'Sukurkite naują restoraną, kad pradėtumėte',

    // Restaurant Board
    'board.title': 'Restorano lenta',
    'board.note': 'užrašas',
    'board.notes': 'užrašai',
    'board.noNotes': 'Užrašų dar nėra. Pridėkite žemiau!',
    'board.addNote': 'Pridėti užrašą į lentą...',
    'board.markedImportant': 'Pažymėta kaip svarbu',
    'board.markImportant': 'Pažymėti kaip svarbų',

    // Menu Designer
    'menu.designer': 'Meniu dizaineris',
    'menu.manageCategoriesItems': 'Valdyti kategorijas ir patiekalus',
    'menu.menusCount': 'meniu',
    'menu.noRestaurant': 'Restoranas nepasirinktas',
    'menu.selectRestaurantFirst': 'Pirmiausia pasirinkite restoraną.',
    'menu.editMenu': 'Redaguoti meniu',
    'menu.createNewMenu': 'Sukurti naują meniu',
    'menu.menuName': 'Meniu pavadinimas',
    'menu.update': 'Atnaujinti',
    'menu.noMenus': 'Meniu dar nėra',
    'menu.clickToManage': 'Spauskite valdyti',
    'menu.deleteMenu': 'Ištrinti meniu',
    'menu.deleteAndAllItems': 'ir visas jo kategorijas bei patiekalus?',
    'menu.menuCreated': 'Meniu sukurtas',
    'menu.menuCreatedDesc': 'Meniu sėkmingai sukurtas.',
    'menu.menuUpdated': 'Meniu atnaujintas',
    'menu.menuUpdatedDesc': 'Meniu sėkmingai atnaujintas.',
    'menu.menuDeleted': 'Meniu ištrintas',
    'menu.menuDeletedDesc': 'Meniu sėkmingai ištrintas.',
    'menu.failedCreate': 'Nepavyko sukurti meniu.',
    'menu.failedUpdate': 'Nepavyko atnaujinti meniu.',
    'menu.failedDelete': 'Nepavyko ištrinti meniu.',
    'menu.addCategory': 'Pridėti kategoriją',
    'menu.editCategory': 'Redaguoti kategoriją',
    'menu.categoryName': 'Kategorijos pavadinimas',
    'menu.noCategories': 'Kategorijų dar nėra',
    'menu.addItem': 'Pridėti patiekalą',
    'menu.editItem': 'Redaguoti patiekalą',
    'menu.itemName': 'Patiekalo pavadinimas',
    'menu.price': 'Kaina',
    'menu.descriptionOptional': 'Aprašymas (Neprivaloma)',
    'menu.noItems': 'Šioje kategorijoje patiekalų nėra',
    'menu.deleteItem': 'Ištrinti patiekalą',
    'menu.deleteCategory': 'Ištrinti kategoriją',
    'menu.deleteCategoryAndItems': 'ir visus jo patiekalus?',
    'menu.categoryCreated': 'Kategorija sukurta',
    'menu.categoryCreatedDesc': 'Kategorija sėkmingai sukurta.',
    'menu.categoryUpdated': 'Kategorija atnaujinta',
    'menu.categoryUpdatedDesc': 'Kategorija sėkmingai atnaujinta.',
    'menu.categoryDeleted': 'Kategorija ištrinta',
    'menu.categoryDeletedDesc': 'Kategorija ištrinta.',
    'menu.failedCreateCategory': 'Nepavyko sukurti kategorijos.',
    'menu.failedUpdateCategory': 'Nepavyko atnaujinti kategorijos.',
    'menu.failedDeleteCategory': 'Nepavyko ištrinti kategorijos.',
    'menu.itemCreated': 'Patiekalas sukurtas',
    'menu.itemCreatedDesc': 'Patiekalas sėkmingai sukurtas.',
    'menu.itemUpdated': 'Patiekalas atnaujintas',
    'menu.itemUpdatedDesc': 'Patiekalas sėkmingai atnaujintas.',
    'menu.itemDeleted': 'Patiekalas ištrintas',
    'menu.itemDeletedDesc': 'Patiekalas ištrintas.',
    'menu.failedCreateItem': 'Nepavyko sukurti patiekalo.',
    'menu.failedUpdateItem': 'Nepavyko atnaujinti patiekalo.',
    'menu.failedDeleteItem': 'Nepavyko ištrinti patiekalo.',
    'menu.invalidPrice': 'Neteisinga kaina',
    'menu.enterValidPrice': 'Įveskite teisingą kainą.',
    'menu.item': 'patiekalas',
    'menu.items': 'patiekalai',

    // Floor Layouts
    'layout.floorLayouts': 'Salės išdėstymai',
    'layout.tables': 'stalai',
    'layout.layouts': 'išdėstymai',
    'layout.editTable': 'Redaguoti stalą',
    'layout.addNewTable': 'Pridėti naują stalą',
    'layout.tableNumber': 'Stalo numeris',
    'layout.description': 'Aprašymas',
    'layout.addTable': 'Pridėti stalą',
    'layout.noTables': 'Stalų dar nėra',
    'layout.table': 'Stalas',
    'layout.editLayout': 'Redaguoti išdėstymą',
    'layout.createNewLayout': 'Sukurti naują išdėstymą',
    'layout.layoutName': 'Išdėstymo pavadinimas',
    'layout.noLayouts': 'Išdėstymų dar nėra',
    'layout.selectLayout': 'Pasirinkti išdėstymą',
    'layout.deleteLayout': 'Ištrinti išdėstymą',
    'layout.deleteLayoutDesc': 'Tai taip pat ištrins visus stalus šiame išdėstyme.',
    'layout.deleteTable': 'Ištrinti stalą',
    'layout.tableAdded': 'Stalas sėkmingai pridėtas.',
    'layout.tableUpdated': 'Stalas sėkmingai atnaujintas.',
    'layout.tableDeleted': 'Stalas sėkmingai ištrintas.',
    'layout.layoutCreated': 'Išdėstymas sėkmingai sukurtas.',
    'layout.layoutUpdated': 'Išdėstymas sėkmingai atnaujintas.',
    'layout.layoutDeleted': 'Išdėstymas sėkmingai ištrintas.',
    'layout.failedCreateTable': 'Nepavyko sukurti stalo.',
    'layout.failedUpdateTable': 'Nepavyko atnaujinti stalo.',
    'layout.failedDeleteTable': 'Nepavyko ištrinti stalo.',
    'layout.failedCreateLayout': 'Nepavyko sukurti išdėstymo.',
    'layout.failedUpdateLayout': 'Nepavyko atnaujinti išdėstymo.',
    'layout.failedDeleteLayout': 'Nepavyko ištrinti išdėstymo.',
    'layout.table1': 'stalas',

    // Help & Support
    'help.title': 'Pagalba ir palaikymas',
    'help.welcomeTitle': 'Sveiki, drąsuoli!',
    'help.welcomeText': 'Radote pagalbos puslapį. Sveikiname. Dauguma žmonių tiesiog panikuoja ir skambina vadybininkui. Jūs jau lenkiate 99% personalo. Ši programa — tarsi Keršytojų būstinė, tik vietoj pasaulio gelbėjimo, jūs gelbite vakarienės užsakymus nuo chaoso.',
    'help.howTitle': 'Kaip čia atsidūriau?',
    'help.howText': 'Kažkas (greičiausiai jūsų viršininkas) patvirtino jūsų paskyrą. Jums buvo priskirtas vaidmuo — Salė, Virtuvė arba Administratorius. Pagalvokite apie tai kaip apie Hogvartso namus, tik niekas pats nepasirenka ir Rūšiavimo Kepurė — tai jūsų vadybininkas. Jei gavote Virtuvę, nesijaudinkite — bent jau ten šilta.',
    'help.buttonsTitle': 'Ką daro visi šie mygtukai?',
    'help.ordersDesc': 'Čia vyksta magija. Priimkite užsakymus kaip profesionalas. Arba bent jau kaip žmogus, kuris labai, labai stengiasi.',
    'help.kitchenDesc': 'Realaus laiko užsakymai virtuvės komandai. Daugiau nereikia žaisti sugadinto telefono per visą restoraną. „AR SAKEI BE SVOGŪNŲ AR SU PAPILDOMAIS?!" — daugiau niekada.',
    'help.workdayDesc': 'Prisijunkite, sekite pamainas, apsimeskite, kad atvykote laiku. (Mes matome laiko žymes, beje.)',
    'help.historyDesc': 'Kiekvienas kada nors padarytas užsakymas. Tai kaip jūsų naršyklės istorija, bet maistui ir iš tikrųjų naudinga.',
    'help.restaurantDesc': 'Tik administratoriams skirta teritorija. Jei matote šią skiltį, arba turite galią, arba radote klaidą. Bet kuriuo atveju, naudokite išmintingai.',
    'help.tipsTitle': 'Profesionalų patarimai',
    'help.tip1': 'Įsidiekite programą telefone. Ji veikia kaip tikra programa! Jūsų telefonas net nesupras skirtumo. Mes apgavome milijonus telefonų visame pasaulyje. (Gerai, gal kokius 4.)',
    'help.tip2': 'Užsakymai atsinaujina realiu laiku visuose įrenginiuose vienu metu. Tai ne magija — tai technologija, kurią kūrėjas praleido per daug naktų kurdamas vietoj miego.',
    'help.tip3': 'Išbandykite tamsų režimą vėlyvose pamainose. Jūsų akių tinklainės parašys jums padėkos laišką.',
    'help.tip4': 'Jei kažkas atrodo sugedę, pabandykite atnaujinti. Jei vis dar sugedę, tai „funkcija". Jei TIKRAI sugedę, kaltinkite kūrėją — jis tikriausiai to nusipelnė.',
    'help.actualHelpTitle': 'Man reikia tikros pagalbos',
    'help.actualHelpText': 'Jei programa užstringa, užsakymai dingsta arba virtuvės ekrane pradeda rodyti kačių video — susisiekite su administratoriumi. Jis tai ištaisys arba persiųs jūsų skundą kūrėjui, kuris jį perskaitys 2 val. nakties ir abejodamas savo gyvenimo pasirinkimais. Bet kuriuo atveju, kažkas atsakys. Tikriausiai. Galiausiai. Nieko nežadame, bet stengsimės.',
    'help.footer': 'Rankomis sukurta su didžiuliais kiekiais kofeino — Justinas Narutis. v1.0.0 — „Mano kompiuteryje veikia" leidimas.',

    // Privacy Policy
    'privacy.title': 'Privatumo politika',
    'privacy.lastUpdated': 'Paskutinį kartą atnaujinta: 2026 m. vasaris. Tikriausiai esate pirmas žmogus, kuris iš tikrųjų atidarė šį puslapį. Esame nuoširdžiai sužavėti. Jūsų mama didžiuotųsi.',
    'privacy.collectTitle': 'Ką renkame (nepanikuokite)',
    'privacy.collectText': 'Renkame jūsų vardą, el. paštą ir pareigas restorane. Tai viskas. Mes nesame CŽV. Mes nežinome jūsų buvimo vietos, naršymo istorijos ar to, kad praėjusį antradienį „Google" ieškojote „kaip profesionaliai atsistatydinti". Taip pat saugome užsakymų duomenis ir pamainų įrašus, nes kažkas turi prisiminti, kad 7-as stalas užsisakė žuvies specialą. Mes NERENKAME: jūsų „Spotify" grojaraščių, „Tinder" aprašymo, prieštaringų picos pagardų nuomonių ar „Netflix" slaptažodžio (nors jei siūlote...).',
    'privacy.useTitle': 'Ką darome su jūsų duomenimis',
    'privacy.useText': 'Naudojame juos restorano programai valdyti. Tiesiogine prasme tik tiek. Apdorojame užsakymus, sekame kas kada dirbo ir generuojame ataskaitas, kurios priverčia viršininką jaustis svarbiu. Mes NEPARDUODAME jūsų duomenų. Mes NESIDALINAME jais su reklamuotojais. Mes NEPREKIAUJAME jais juodojoje rinkoje. Net nežiūrime į juos pramogai. Sąžiningai, jūsų užsakymų istorija nėra tokia įdomi. (Nors tas, kuris vis užsisako papildomos duonos — mes jus matome ir gerbiame.)',
    'privacy.whereTitle': 'Kur gyvena jūsų duomenys',
    'privacy.whereText': 'Jūsų prisijungimo duomenys gyvena „Firebase" (tai „Google" — taip, TAS „Google", kuris žino viską apie visus, išskyrus mus, nes mes nesidalijame). Jūsų restorano duomenys gyvena serveryje, kurį kūrėjas asmeniškai saugo savo gyvybe. Na, ne gyvybe, bet bent jau stipriu slaptažodžiu. Viskas užšifruota HTTPS/SSL, o tai reiškia „įsilaužėliams būtų lengviau įsilaužti į Fort Knox". Jūsų duomenys kopijuojami kasdien, nes, skirtingai nuo jūsų buvusio(-ios), mes tikime antromis galimybėmis ir niekada neprarandame to, kas svarbu.',
    'privacy.rightsTitle': 'Jūsų šventos teisės',
    'privacy.right1': 'Galite paprašyti pamatyti visus duomenis, kuriuos turime apie jus. Spoileris: tai jūsų vardas, el. paštas ir tas kartas, kai netyčia išsiuntėte užsakymą 47 sriuboms.',
    'privacy.right2': 'Galite paprašyti administratoriaus ištrinti jūsų paskyrą. Mums bus liūdna, bet išgyvensime. Tikriausiai.',
    'privacy.right3': 'Galite bet kada pakeisti slaptažodį. Prašome, nedarykite jo „password123". Maldaujame.',
    'privacy.right4': 'Turite teisę skųstis. Mes turime teisę atsakyti gūžtelėjimo emoji. Bet vis tiek stengsimės tai ištaisyti.',
    'privacy.right5': 'Turite teisę likti sumišę. Viskas, ką paspausite, gali ir bus panaudota maisto užsakymui priimti.',
    'privacy.cookiesTitle': 'Slapukai (deja, skaitmeniniai)',
    'privacy.cookiesText': 'Naudojame VIENĄ rūšį slapukų: tokius, kurie laiko jus prisijungusius, kad nereikėtų įvesti slaptažodžio 47 kartus per pamainą. Jokių reklaminių slapukų. Jokių sekimo pikselių. Jokių šiurpių „pastebėjome, kad žiūrėjote sportbačius" reklamų, persekiojančių jus po visą internetą. Vieninteliai slapukai, kurie mums tikrai rūpi, yra šokoladiniai sausainiai desertų meniu. Beje, ar juos ragavote? Jie puikūs. Tai nėra remiamas pranešimas — mums tiesiog labai patinka sausainiai.',
    'privacy.changeTitle': 'Ar ši politika keisis?',
    'privacy.changeText': 'Galbūt. Bet jei keisis, žadame, kad ji vis tiek bus parašyta žmogaus, kuris mano, kad teisiniai dokumentai turėtų būti skaitomi be teisės diplomo ir trijų espreso. Niekada neįterpsime „naudodami šią programą sutinkate atiduoti mums savo pirmagimį" sąlygų. Pažadame.',
    'privacy.footer': 'Klausimai? Skundai? Egzistencinės krizės? Susisiekite su administratoriumi. Jis apsimes žinantis atsakymą.',
  },
} as const;

const LanguageContext = createContext<LanguageContextType | null>(null);

export function LanguageProvider({ children }: { children: React.ReactNode }) {
  const [language, setLanguageState] = useState<Language>(() => {
    // Load from localStorage or default to 'en'
    const saved = localStorage.getItem('app-language');
    return (saved === 'lt' ? 'lt' : 'en') as Language;
  });

  const setLanguage = useCallback((lang: Language) => {
    setLanguageState(lang);
    localStorage.setItem('app-language', lang);
  }, []);

  const t = useCallback((key: keyof TranslationKeys): string => {
    return translations[language][key] || key;
  }, [language]);

  const formatPrice = useCallback((price: number): string => {
    if (language === 'lt') {
      return new Intl.NumberFormat('lt-LT', {
        style: 'currency',
        currency: 'EUR',
      }).format(price);
    }
    return new Intl.NumberFormat('en-US', {
      style: 'currency',
      currency: 'USD',
    }).format(price);
  }, [language]);

  useEffect(() => {
    // Update document language attribute
    document.documentElement.lang = language;
  }, [language]);

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t, formatPrice }}>
      {children}
    </LanguageContext.Provider>
  );
}

export function useLanguage() {
  const context = useContext(LanguageContext);
  if (!context) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
}
